name: Build ARM64 Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for tags

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential crossbuild-essential-arm64 qemu-user-static

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Get version from tag
      id: get_version
      run: |
        # Remove 'v' prefix from tag name
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build ARM64 binary
      run: |
        # Create a build directory
        mkdir -p rpi5_client/bin

        # Cross-compile for ARM64
        cd rpi5_client
        CC=aarch64-linux-gnu-gcc CFLAGS="-static" make

        # Verify the binary architecture
        file bin/fan_temp_daemon

    - name: Build Debian package
      run: |
        # Build the Debian package with version from tag
        cd rpi5_client
        VERSION=${{ steps.get_version.outputs.version }} ./scripts/build_deb.sh

        # Move the package to a predictable location
        mkdir -p ../artifacts
        mv rpi5-fan-temp-daemon-*.deb ../artifacts/

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: rpi5-fan-temp-daemon-arm64
        path: artifacts/*.deb

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.deb
        name: Release ${{ steps.get_version.outputs.version }}
        tag_name: v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
